### ISSUE TITLE
Daemon needs to handle Bungeecord servers listening addresses

### ISSUE THREAD

**Issue by DaneEveritt** [Pterodactyl/Panel#175]
Current config sample:
```
servers:
  lobby:
    motd: '&1Just another BungeeCord - Forced Host'
    address: 127.0.0.1:25565
    restricted: false
```

The daemon needs to handle 127.0.0.1 and replace it with the `pterodactyl0` interface IP so that things will work correctly.

-----
Also for discussion is better handling of the routing for this to begin with, especially if servers are on different nodes where localhost wouldn't work properly.
