### ISSUE TITLE
[Feature Request] Use docker networks aliases

### ISSUE THREAD

**Issue by NoxInmortus** [pterodactyl/panel#1947]
Hello,

I would like to ask for the containers to use network aliases.

Example :

```
  - name: MyGame
    image: user/mygame
    networks:
      - name: pterodactyl_nw
        aliases:
          - mygame

  - name: MyGamePlugin
    image: user/mygameplugin
    networks:
      - name: pterodactyl_nw
        aliases:
          - mygameplugin
```

When a Game server has some kind of addons/plugins app which can bind to them to provide additional features (like the JTS3 Teamspeak3 mod for exemple), using docker networks aliases allow them to connect to each others through the docker network (which is then faster and more reliable than any other options).

Of course, you can already do that, by using the docker container id as it is present in `/etc/hosts`, but using a user-defined name is always better and needs less actions from the user side.

We could use the `Server Name` pterodactyl servers parameter, or let the user set it in a new parameter entry.

To set it by default as the `Server Name` and let it be overridable by a new parameter entry sounds right.
