### ISSUE TITLE
Button to open console in a separate window (Like in <1.0.x)

### ISSUE THREAD

**Issue by realkarmakun** [pterodactyl/panel#2584]
**Describe the solution you'd like**
A button that opens separate window with server's console.

**Additional context**
It was a really useful feature for server management. I believe it was just overlooked so this is just a reminder.

**Comment by Artuto** [comment]
Bump.

**Comment by realkarmakun** [comment]
Still relevant. We have about 16+ servers and every single one of them needs to be monitored. Having them all on one screen in separate windows was very handy

**Comment by SirJimmothy** [comment]
I've made a CSS injection workaround for this until this is fixed:

```css
.piqbQ.sc-1j2y518-1, .byVPsx.sc-19da077-1, .jWBQCE.sc-19da077-0, .fade-enter-done.fade-appear-done.cWFcHc.lfuaoi-0, .fOFvgZ.tupl2x-2, .fNmetC.kbxq2g-3, .x3r2dw-0.kbxq2g-2.evldyg.fhnXAb { display: none; }

#terminal, #ltr, .x3r2dw-0, .itaf37-3, .xterm-screen, .xterm-text-layer, .xterm-selection-layer, .xterm-link-layer, .xterm-cursor-layer, .itaf37-2.intSrw { height: 100%; }

.x3r2dw-0, .iyAtmz { margin: 0; }

.itaf37-3 { height: calc(100% - 3.5em); }
```

I've only tested this in Edge, but it should be effective in most browsers.
