### ISSUE TITLE
[Wings] Can't use private docker registry with authentication for installation containers

### ISSUE THREAD

**Issue by Mintux** [pterodactyl/panel#2589]
**Background (please complete the following information):**
* Panel or Daemon: Daemon
* Version of Panel/Daemon: 1.0.2 (Panel) & 1.0.1 (Daemon)
* Server's OS: Debian 10.6 (Buster)
* Your Computer's OS & Browser: Windows 10 Home 64 Bit / Firefox

**Describe the bug**
Using a private image for the installation container fails when it requires authentication. Seems like Wings only accepts the private authenticated images for the gameserver container itself, not for installation scripts.

If you use a private image with correct authentication in the installation script area of your egg, the install process from a new server aborts with this message:

```
ERROR: [Oct 24 02:17:07.870] failed to run install process for server error=failed to pull updated installation container image for server: Error response from daemon: Get https://registry.domain.tld/v2/redacted/development/gameserver/images/manifests/debian_base: denied: access forbidden server=00b733f6-f72b-4d17-9dab-82fb4fe7b41c
```

I can confirm that the authentication area in the config.yml is correct, since the Daemon can pull images for the gameserver container itself, but not for installation containers.

**To Reproduce**
1. Go to your custom egg configuration and use a private docker image for the installation container
1.2. For example: registry.domain.tld/redacted/development/gameserver/images:debian_base
2. Try to install a new server
3. See error in wings log

**Expected behavior**
Private docker images should also be available for installation containers.

**Comment by rxdn** [comment]
Pterodactyl won't use the Docker credentials from ~/.docker/config.json: You need to provide them in your `/etc/pterodactyl/config.yml` like so:

```yaml
...
docker:
  ...
  registries:
    registry.example.com:
      username: username_here
      password: password_here
...
```

**Comment by Mintux** [comment]
@rxdn That was already done. As described in the issue description this is only working for server containers but not for the image used as installation container.

**Comment by rxdn** [comment]
Didn't fully read the issue, my apologies

**Comment by matthewpi** [comment]
I think that we should continue with installation even if the image fails to pull as long as it exists locally (the same behavior that starting a server has).

**Comment by Maelep** [comment]
Is this issue solved? Because I tried:
```yml
registries:
  registry.hub.docker.com:
    username: myUsername
    password: myToken
```
but it doesn't pull the image.

**Comment by rostov114** [comment]
I will answer myself and others

If you use a docker image like this in your egg
`username/repository:tag`

That is, standard Docker repositories.

Then your registry should look like
```yaml
  registries:
    username/repository:
      username: myUsername
      password: myPassword
```
