### ISSUE TITLE
filesystem: invalid path resolution in LXC box

### ISSUE THREAD

**Issue by Bixilon** [pterodactyl/panel#2640]
**Background (please complete the following information):**
* Panel or Daemon: Wings
* Version of Panel/Daemon: 1.0.1
* Server's OS: Ubuntu 20.04
* Your Computer's OS & Browser: Not important (but Firefox on Ubuntu)

**Describe the bug**
```
Client:
 Debug Mode: false

Server:
 Containers: 11
  Running: 0
  Paused: 0
  Stopped: 11
 Images: 4
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-47-generic
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 5
 Total Memory: 11.18GiB
 Name: minecraft1
 ID: HX3B:ELFH:XAVR:7A5J:C2NJ:WBYE:HH6R:H2MS:ICLS:MEGL:OBAL:77JI
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

```
Linux minecraft1 5.4.0-47-generic #51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

I upgraded from the legacy nodejs daemon to wings. Wings can communicate with the panel, ... If I want to start a server, look at the files (No matter if sftp or web based file explorer), I receive an 500 Error. You can find a stack trace below. The only difference to a common server is, that it is a lxc box (security privileged). Docker works fine in it (tested with hello world) and the legacy version also worked without a issue. The fault is not a bug in the panel, I setup a second version of wings (not in a container) and it worked. I have no clue whats wrong, can you help me?

Wings stacktrace:
```
ERROR: [Nov  1 16:32:44.039] encountered HTTP/500 error while handling request error=filesystem: invalid path resolution error_id=4551e31e-0a01-4ca5-a6f4-9c882b2c841a server=6ef4fbe2-e37c-4112-877a-3485c9d0fd5d

Stacktrace:
github.com/pterodactyl/wings/server/filesystem.init
        /home/runner/work/wings/wings/server/filesystem/errors.go:12
runtime.doInit
        /opt/hostedtoolcache/go/1.15.2/x64/src/runtime/proc.go:5625
runtime.doInit
        /opt/hostedtoolcache/go/1.15.2/x64/src/runtime/proc.go:5620
runtime.doInit
        /opt/hostedtoolcache/go/1.15.2/x64/src/runtime/proc.go:5620
runtime.doInit
        /opt/hostedtoolcache/go/1.15.2/x64/src/runtime/proc.go:5620

DEBUG: [Nov  1 16:32:44.041] GET /api/servers/6ef4fbe2-e37c-4112-877a-3485c9d0fd5d/files/list-directory?directory=%252F client_ip=127.0.0.1 latency=2.056691ms status=500
```

LXC config:
```
architecture: x86_64
config:
  image.architecture: amd64
  image.description: ubuntu 20.04 LTS amd64 (release) (20200504)
  image.label: release
  image.os: ubuntu
  image.release: focal
  image.serial: "20200504"
  image.type: squashfs
  image.version: "20.04"
  limits.cpu: "5"
  limits.memory: 12GB
  raw.lxc: |
    lxc.cgroup.devices.allow = a
    lxc.cap.drop =
  security.nesting: "true"
  security.privileged: "true"
  volatile.base_image: 647a85725003d873f8bb9a5bd1a09bdc7fd4bcb393b2cf629f7e0edaa58f5637
  volatile.eth0.host_name: vethd387dd07
  volatile.eth0.hwaddr: 00:16:3e:e9:94:9b
  volatile.idmap.base: "0"
  volatile.idmap.current: '[]'
  volatile.idmap.next: '[]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: RUNNING
devices:
  srv_pterodactyl:
    path: /srv/minecraft/
    source: /srv/minecraft/pterodactyl/
    type: disk
  srv_ssl:
    path: /srv/ssl
    source: /srv/ssl/
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: "
```

** Steps To Reproduce **
1. Install lxc (on Debian based: `sudo snap install lxd`)
2. Launch a container with `lxc launch ubuntu:focal wings`
3. Install wings (see official Docs)
4. Install a server on the newly created node
5. Open the file explorer for this server
