### ISSUE TITLE
[Not resolved] Problem with files contains 'config.yml' in their name.

### ISSUE THREAD

**Issue by Micorksen** [pterodactyl/panel#3565]
Hello,
I have a problem with the files contains 'config.yml' in their name.
I go to my folder with some files and open 'config.yml' or 'TestConfig.yml'; and error is showed. 

![image](https://user-images.githubusercontent.com/35396314/130364425-e9028e7d-0570-4ec2-a5f6-92a8f28519c6.png)

I'm checking the requests of my browser, and the request to get the contents of the file is returned with 422 error.
![image](https://user-images.githubusercontent.com/35396314/130364446-da5266f5-2de5-4b45-a10c-2142d58390aa.png)

This is the response.
![image](https://user-images.githubusercontent.com/35396314/130364457-cfb35cd3-9f90-49e2-9cdb-9a0d938ae3b1.png)

Can you help me please ?
Good bye by the way !

**Comment by parkervcp** [comment]
Can you share the contents of that config.yml?

**Comment by Micorksen** [comment]
Hello,
It's just a minecraft configuration... But okay ?

```
# TownyFlight by LlmDl.
Version: 1.7.0
# Prefix to messages seen in game.
pluginPrefix: '&8[&3TownyFlight&8] '
####################
# Language Strings #
####################

language:
  # Message shown when flight activated.
  flightOnMsg: 'Flight Activated. '
  # Message shown when flight de-activated.
  flightOffMsg: 'Flight De-activated. '
  # Message shown when player lacks a town. 
  noTownMsg: 'Flight cannot be activated, you don''t belong to a town. '
  # Message shown when flight cannot be turned on.
  notInTownMsg: 'Flight cannot be activated, return to your town and try again. '
  # Message shown when a player has flight taken away.
  flightDeactivatedMsg: 'Left town boundaries. '
  # Message shown when a player has flight taken away because of PVP.
  flightDeactivatedPVPMsg: 'Entering PVP combat. '
  # Message shown when a player has flight taken away by console.
  flightDeactivatedConsoleMsg: 'Flight priviledges removed. '
  # Message shown when a player lacks a permission node.
  noPermission: 'You do not have permission for this command, missing: '
  # Message shown when war is active and flight is disallowed.
  notDuringWar: 'You cannot use flight while Towny war is active. '
  # Message telling a player to return to an allowed flight area.
  returnToAllowedArea: 'You have %s seconds to return to an allowed flight area. '
#################
#    Options    #
#################

options:
  # If set to true, players entering their town will have flight auto-enabled.
  # When set to true, the plugin will use slightly more resources due to the EnterTown listener.
  auto_Enable_Flight: 'false'
  # If set to true, players entering their town will have flight auto-enabled without being notified in chat.
  auto_Enable_Silent: 'false'
  # If set to false, players can still fly in their town while war is active.
  disable_During_Wartime: 'true'
  # If set to false, TownyFlight will not prevent combat of flying people.
  disable_Combat_Prevention: 'false'
  # If set to false, the language.noPermission message will not display the permission node.
  show_Permission_After_No_Permission_Message: 'true'
  # Number of seconds after leaving an allowed flight area before flight is taken away.
  # Set to 0 to take flight away immediately.
  flight_Disable_Timer: '3'
```

Good bye !
