### ISSUE TITLE
Interface pterodactyl0 created but wings still wants to create one

### ISSUE THREAD

**Issue by Tristaan** [pterodactyl/panel#3585]
### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.

### Current Behavior

I create the interface WITH name inside docker-compose.yml like so:
```yaml
version: '3.8'

services:

  wings:
    image: ghcr.io/pterodactyl/wings:v1.4.4
    env_file:
      - .env
    restart: always
    networks:
      - web
      - pterodactyl0
    ports:
      - "2022:2022"
    tty: true
    environment:
      TZ: "UTC"
      WINGS_UID: 988
      WINGS_GID: 988
      WINGS_USERNAME: pterodactyl
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/docker/containers/:/var/lib/docker/containers/"
      - "${DATA_DIR}/wings/etc/:/etc/pterodactyl/"
      - "/var/lib/pterodactyl/:/var/lib/pterodactyl/"
      - "/var/log/pterodactyl/:/var/log/pterodactyl/"
      - "/tmp/pterodactyl/:/tmp/pterodactyl/"
      - "/etc/ssl/certs:/etc/ssl/certs:ro"
    labels:
      - "traefik.http.routers.pterodactyl-wings.rule=Host(`${TRAEFIK_WINGS_DOMAIN}`)"
      - "traefik.http.routers.pterodactyl-wings.tls=true"
      - "traefik.http.services.pterodactyl-wings.loadbalancer.server.port=80"
      - "traefik.http.routers.pterodactyl-wings.tls.certresolver=letsencrypt"

networks:
  web:
    external: true
  pterodactyl0:
    name: pterodactyl0
    driver: bridge
    ipam:
      config:
        - subnet: "172.100.0.0/16"
    driver_opts:
      com.docker.network.bridge.name: pterodactyl0
```
but wings still wants to create an interface with the same name, thus throwing error below.

The address space is **not** used by anything other than the interface created with docker-compose.yml
I also tried using only the web network, but still error. the web network is used for traefik.

### Expected Behavior

I expect it to take the already existing interface, not try to create a new one. atleast create one without using an address space that's already in use.

### Steps to Reproduce

Take docker-compose.yml setup and run it with this server configuration inside DATA_DIR:
```yaml
debug: true
uuid: fd885856-62e6-4548-ba5b-610d6b181e72
token_id: hv3H8iQTp2jdJxb1
token: qqLAFrZRFQI81O4ZMOQOrMMVyJB35XsX8mG9ZQn0o6x5iX6q1H1fDX9iRiObdYDt
api:
  host: 0.0.0.0
  port: 80
  ssl:
    enabled: true
    cert: /etc/letsencrypt/live/node.example.com/fullchain.pem
    key: /etc/letsencrypt/live/node.example.com/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'https://panel.example.com'
```

### Panel Version

1.5

### Wings Version

1.4.4

### Error Logs

```bash
wings_1  |                      ____
wings_1  | __ Pterodactyl _____/___/_______ _______ ______
wings_1  | \_____\    \/\/    /   /       /  __   /   ___/
wings_1  |    \___\          /   /   /   /  /_/  /___   /
wings_1  |         \___/\___/___/___/___/___    /______/
wings_1  |                             /_______/ v1.4.4
wings_1  |
wings_1  | Copyright �� 2018 - 2021 Dane Everitt & Contributors
wings_1  |
wings_1  | Website:  https://pterodactyl.io
wings_1  |  Source:  https://github.com/pterodactyl/wings
wings_1  | License:  https://github.com/pterodactyl/wings/blob/develop/LICENSE
wings_1  |
wings_1  | This software is made available under the terms of the MIT license.
wings_1  | The above copyright notice and this permission notice shall be included
wings_1  | in all copies or substantial portions of the Software.
wings_1  |
wings_1  | DEBUG: [Aug 26 22:03:55.111] running in debug mode
wings_1  |  INFO: [Aug 26 22:03:55.111] loading configuration from file config_file=/etc/pterodactyl/config.yml
wings_1  |  INFO: [Aug 26 22:03:55.112] configured wings with system timezone timezone=UTC
wings_1  | DEBUG: [Aug 26 22:03:55.112] ensuring root data directory exists path=/var/lib/pterodactyl
wings_1  | DEBUG: [Aug 26 22:03:55.112] ensuring server data directory exists path=/var/lib/pterodactyl/volumes
wings_1  | DEBUG: [Aug 26 22:03:55.113] ensuring archive data directory exists path=/var/lib/pterodactyl/archives
wings_1  | DEBUG: [Aug 26 22:03:55.113] ensuring backup data directory exists path=/var/lib/pterodactyl/backups
wings_1  |  INFO: [Aug 26 22:03:55.113] checking for pterodactyl system user username={0 0}
wings_1  |  INFO: [Aug 26 22:03:55.114] configured system user successfully gid=988 uid=988 username=pterodactyl
wings_1  |  INFO: [Aug 26 22:03:55.114] fetching list of servers from API
wings_1  | DEBUG: [Aug 26 22:03:55.115] making request to external HTTP endpoint endpoint=https://panel.example.com/api/remote/servers?page=0&per_page=50 headers=map[Accept:[application/vnd.pterodactyl.v1+json] Authorization:[(redacted)] Content-Type:[application/json] User-Agent:[Pterodactyl Wings/vv1.4.3 (id:hv3H8iQTp2jdJxb1)]] method=GET
wings_1  |  INFO: [Aug 26 22:03:55.596] processing servers returned by the API total_configs=1
wings_1  | DEBUG: [Aug 26 22:03:55.597] using 16 workerpools to instantiate server instances
wings_1  |  INFO: [Aug 26 22:03:55.597] creating new server object from API response server=0a6704f8-5b0a-4367-ae0e-225f3b437e5b
wings_1  | DEBUG: [Aug 26 22:03:55.598] registering event listeners: console, state, resources... server=0a6704f8-5b0a-4367-ae0e-225f3b437e5b
wings_1  | DEBUG: [Aug 26 22:03:55.599] syncing stop configuration with configured docker environment server=0a6704f8-5b0a-4367-ae0e-225f3b437e5b
wings_1  |  INFO: [Aug 26 22:03:55.599] finished processing server configurations duration=2.723922ms
wings_1  |  INFO: [Aug 26 22:03:55.602] creating missing pterodactyl0 interface, this could take a few seconds...
wings_1  | FATAL: [Aug 26 22:03:55.603] failed to configure docker environment error=Error response from daemon: Pool overlaps with other one on this address space
wings_1  |
wings_1  | Stacktrace:
wings_1  | Error response from daemon: Pool overlaps with other one on this address space
wings_1  |
```

**Comment by parkervcp** [comment]
The config in the compose file was set up the the way it was because it avoided overlapping the pterodactyl0 network.

Wings creates a network on startup and it's trying to configure it to it's specified ranges. You caused this by creating your own pterodactyl0 network but not setting it in the wings config.

**Comment by Tristaan** [comment]
Thanks, I found the configuration directives by browsing the code [here](https://github.com/pterodactyl/wings/blob/develop/config/config_docker.go). Maybe those configuration settings could be documented. Sadly I didn't know that they even exist.

**Comment by parkervcp** [comment]
You mean like they are documented here - https://pterodactyl.io/wings/1.0/configuration.html#custom-network-interfaces

**Comment by Mist-Hunter** [comment]
> You mean like they are documented here - https://pterodactyl.io/wings/1.0/configuration.html#custom-network-interfaces

Thank you @parkervcp, for some reason that documentation didn't click with me. I kept trying to find additional syntax for the yaml file and couldn't (something besides the host network example). I'm sure it's a mistake / failure on my part, however, I noticed your "Support Bot" in Discord seems prepped to answer this issue with a very helpful example in case people come here first (like I did)

Do you know where I might fight official documentation on the configuration options that are demonstrated below?

From: https://discord.com/channels/122900397965705216/493443725012500490/838475977738420284
>Default wings network docker config template if you are having overlapping networks and can't generate it. Copy it into your config.yml and change the occurrences of 172.18.0.x to something that's not already in use by your other networks. For example, 172.20.0.1
``` yaml
docker:
  network:
    interface: 172.18.0.1
    dns:
    - 1.1.1.1
    - 1.0.0.1
    name: pterodactyl_nw
    ispn: false
    driver: bridge
    network_mode: pterodactyl_nw
    is_internal: false
    enable_icc: true
    interfaces:
      v4:
        subnet: 172.18.0.0/16
        gateway: 172.18.0.1
      v6:
        subnet: fdba:17c8:6c94::/64
        gateway: fdba:17c8:6c94::1011
  domainname: ""
  registries: {}
  tmpfs_size: 100
```
