### ISSUE TITLE
Strange 500 Server Error

### ISSUE THREAD

**Issue by StanislasSiweck** [pterodactyl/panel#4330]
### Current Behavior

Hello,
I have a problem of 500 Server Error when I want to delete a node or a server.
I don't know where it comes from, I have no log and no information about why and how it doesn't work.
All in docker.
I have a traefik, I think it could be that.
URL fail :
- /admin/nodes/view/{nodeID}/settings
- /admin/servers/view/{serversID}/delete

I have no more information, I put you my docker-compose in pass ^^

```yml
version: '3.8'
services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
    environment:
      - "OVH_ENDPOINT=ovh-eu"
      - "OVH_APPLICATION_KEY="
      - "OVH_APPLICATION_SECRET="
      - "OVH_CONSUMER_KEY="
      # - CF_API_KEY=YOU_API_KEY
      # be sure to use the correct one depending on if you are using a token or key
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/stan/traefik/data/traefik.yml:/traefik.yml:ro
      - /home/stan/traefik/data/acme.json:/acme.json
      - /home/stan/traefik/data/config.yml:/config.yml:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`traefik.domain.net`)"
      - "traefik.http.middlewares.traefik-auth.basicauth.users="
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.domain.net`)"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=ovh"
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=domain.net"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.domain.net"
      - "traefik.http.routers.traefik-secure.service=api@internal"

networks:
  proxy:
    external: true
  private-proxy:
    external: false
```

[docker-compose-pterodactyl.yml.txt](https://github.com/pterodactyl/panel/files/9387110/docker-compose-pterodactyl.yml.txt)

### Expected Behavior

Its delete the server or the node.

### Steps to Reproduce

- Create panel
- Create node
- Edit node and update
- 500 Server Error

### Panel Version

latest

### Wings Version

latest

### Is there an existing issue for this?

- [x] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by notAreYouScared** [comment]
Without the error logs from the panel, we have no way to assist.

**Comment by StanislasSiweck** [comment]
![image](https://user-images.githubusercontent.com/59709960/185764122-ab296b32-8e16-45fc-9bec-d9b7e7f9edb6.png)
![image](https://user-images.githubusercontent.com/59709960/185764090-1aa75731-fb75-4809-890f-9309cba48c5b.png)

I don't have any log, I don't know why the error doesn't want to create one. Is there any way to have a debug of the requests to see where it stops?  
I tried on another VM and it does the same thing, either my installer has a problem or my infrastructure causes this problem?

**Comment by parkervcp** [comment]
They might be in the container if the folder doesn't show it.

**Comment by StanislasSiweck** [comment]
![image](https://user-images.githubusercontent.com/59709960/185792414-e7a12903-227a-4863-87e3-e5c4107cdab2.png)
I had looked in the container there is nothing too. (the volume worked well because I made test by creating file at a time)
Isn't there a debug mode like with Laravel ? DEBUG=TRUE and with which we could have more info on what's going on?
Or a verbose to get the info in the container  ?

**Comment by StanislasSiweck** [comment]
![image](https://user-images.githubusercontent.com/59709960/185869516-16c119c6-3e1a-4b68-87c9-6ff23257d696.png)
I tried on the API to see and it gives me the same thing :p

**Comment by StanislasSiweck** [comment]
![image](https://user-images.githubusercontent.com/59709960/185944866-4cabe94c-0254-4d73-9505-70c497cdf350.png)
Obviously it crashes here, you know how I can go further? or what it could be?

**Comment by StanislasSiweck** [comment]
![image](https://user-images.githubusercontent.com/59709960/185950850-605b7146-4d8d-48ab-866a-aba1ba64bcf4.png)

Well, I found it.
Basically, the problem was the logs, he didn't have permission.  On root (or www-data for test) I had the error 500, when I put nginx it worked.
To patch ?
@AreYouRlyScared @parkervcp

**Comment by parkervcp** [comment]
Might need to update the image

**Comment by dy1io** [comment]
I confirmed this is what the issue was for me in #4313. Once I set the owner to nginx inside the container I could force delete, logs started working, and no more 500 error. I'll close my issue out but updating the image is probably necessary here like you said.

**Comment by parkervcp** [comment]
The image is definitely set to use nginx in the container. I have no idea how you got to having the www-data as the owner.

https://github.com/pterodactyl/panel/blob/develop/Dockerfile#L26

**Comment by dy1io** [comment]
Hmm, I see that but I'm just pulling the image from `ghcr.io/pterodactyl/panel` like normal and as far as I know it was a clean copy while this was occurring. I'll dig into it when I get some time and if I find anything useful I'll open an issue/PR. Either way I appreciate the help; this has been plaguing me for a while and I'm happy to at the very least have a work around now.

**Comment by dejor** [comment]
I think the problem is caused by how docker compose mounts bind volumes.
If the source directory exists on the host, docker mounts it with the permissions defined on the host.
Otherwise, it will create the directory with root as the owner and mount it as root.
This will overwrite the `chown -R nginx:nginx .` done in the Dockerfile, because the mounting is done after the image is build.

Using named docker volumes instead of bind volumes fixes the issue. E.g. like this:
```yaml
services:
  database:
    image: mariadb:10.5
    restart: always
    networks:
      - pterodactyl
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - database:/var/lib/mysql
    environment:
      *
      *
      *
  cache:
    image: redis:alpine
    restart: always
    networks:
      - pterodactyl
  panel:
    image: ghcr.io/pterodactyl/panel:latest
    restart: always
    networks:
      - proxy
      - pterodactyl
    links:
      - database
      - cache
    volumes:
      - panel-var:/app/var
      - panel-logs:/app/storage/logs
    environment:
      *
      *
      *
volumes:
  panel-logs:
  panel-var:
  database:
networks:
  *
  *
  *
```
