### ISSUE TITLE
Stuck on server installation

### ISSUE THREAD

**Issue by MaximeCn** [pterodactyl/panel#4972]
### Current Behavior

Hello,

I want to run Satisfactory server.

I tried to install pterodactyl and wings with my docker + traefik home configuration but i'm stuck.

My node is pointing to my wing subdomain name.
My panel has his own subdomain name.

My node is up : 
![image](https://github.com/pterodactyl/panel/assets/11914187/e211afcb-bad5-49d5-b11d-e83f736fb1dd)

I created my satisfactory server from egg and now I'm stuck on "Installing" : 

![image](https://github.com/pterodactyl/panel/assets/11914187/f17c30c9-c924-40d9-b8ed-bafff3195faf)

Someone can help me please ?

My node configuration : 
![image](https://github.com/pterodactyl/panel/assets/11914187/9e9eae50-1212-4b2c-bcf8-a6552a78f1d4)

My config.yml configuration : 

```
debug: false
uuid: censured
token_id: censured
token: censured
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/172.18.0.27/fullchain.pem
    key: /etc/letsencrypt/live/172.18.0.27/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'https://gameserver.mydomain.com'
docker:
  network:
    interface: 172.21.0.1
    name: wings0
    ispn: false
    driver: bridge
    network_mode: wings0
    is_internal: false
    enable_icc: true
    interfaces:
      v4:
        subnet: 172.21.0.0/16
        gateway: 172.21.0.1
allowed_origins:
  - '*'
```

My wings docker-compose.yml : 

```
version: '3.8'

services:
  wings:
    image: ghcr.io/pterodactyl/wings:v1.6.1
    container_name: wings0
    networks:
      - wings0
      - web
    #ports:
    #  - "8080:8080"
    #  - "2022:2022"
    #  - "443:443"
    tty: true
    environment:
      TZ: "UTC"
      WINGS_UID: 0
      WINGS_GID: 0
      WINGS_USERNAME: pterodactyl
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/docker/containers/:/var/lib/docker/containers/"
      - "/etc/ssl/certs:/etc/ssl/certs:ro"
      - "./etc/:/etc/pterodactyl/"
      - "./var/lib/:/var/lib/pterodactyl/"
      - "./var/log/:/var/log/pterodactyl/"
      - "./tmp/:/tmp/pterodactyl/"
      # you may need /srv/daemon-data if you are upgrading from an old daemon
      #- "/srv/daemon-data/:/srv/daemon-data/"
      # Required for ssl if you use let's encrypt. uncomment to use.
      #- "/etc/letsencrypt/:/etc/letsencrypt/"

networks:
  web:
    external: true
  wings0:
    name: wings0
    driver: bridge
    ipam:
      config:
        - subnet: "172.21.0.0/16"
    driver_opts:
      com.docker.network.bridge.name: wings0
```

My panel docker-compose : 

```
version: '3.8'

x-common:
  database:
    &db-environment
    # Do not remove the "&db-password" from the end of the line below, it is important
    # for Panel functionality.
    MYSQL_PASSWORD: &db-password "censured"
    MYSQL_ROOT_PASSWORD: "censured"
  panel:
    &panel-environment
    APP_URL: "https://gameserver.mydomain.com"
    # A list of valid timezones can be found here: http://php.net/manual/en/timezones.php
    APP_TIMEZONE: "UTC"
    APP_SERVICE_AUTHOR: "noreply@mydomain.com"
    TRUSTED_PROXIES: "*"
    PUID: 0
    PGID: 0
    # Uncomment the line below and set to a non-empty value if you want to use Let's Encrypt
    # to generate an SSL certificate for the Panel.
    # LE_EMAIL: ""
  mail:
    &mail-environment
    MAIL_FROM: "noreply@mydomain.com"
    MAIL_DRIVER: "smtp"
    MAIL_HOST: "mail"
    MAIL_PORT: "1025"
    MAIL_USERNAME: ""
    MAIL_PASSWORD: ""
    MAIL_ENCRYPTION: "true"

#
# ------------------------------------------------------------------------------------------
# DANGER ZONE BELOW
#
# The remainder of this file likely does not need to be changed. Please only make modifications
# below if you understand what you are doing.
services:
  database:
    image: mariadb:10.5
    container_name: pterodactyl_db
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./srv/database:/var/lib/mysql"
    environment:
      <<: *db-environment
      MYSQL_DATABASE: "panel"
      MYSQL_USER: "pterodactyl"

  cache:
    image: redis:alpine
    container_name: pterodactyl_cache

  panel:
    image: ghcr.io/pterodactyl/panel:latest
    container_name: pterodactyl_panel
    #command: sh -c "chown -R nginx:nginx /app/storage/logs/"
    #ports:
    #  - "80:80"
    #  - "443:443"
    links:
      - database
      - cache
    volumes:
      - "./srv/var/:/app/var/"
      - "./srv/nginx/:/etc/nginx/http.d/"
      - "./srv/certs/:/etc/letsencrypt/"
      - "./srv/logs/:/app/storage/logs"
    environment:
      <<: [*panel-environment, *mail-environment]
      DB_PASSWORD: *db-password
      APP_ENV: "production"
      APP_ENVIRONMENT_ONLY: "false"
      CACHE_DRIVER: "redis"
      SESSION_DRIVER: "redis"
      QUEUE_DRIVER: "redis"
      REDIS_HOST: "cache"
      DB_HOST: "database"
      DB_PORT: "3306"
    networks:
      - web
      - default

networks:
  web:
    external: true
  default:
    ipam:
      config:
        - subnet: 172.20.0.0/16
```

### Expected Behavior

The  server installation must finish after few minutes but i'm stuck for more than 2 hours.

When I try to start the server : 

![image](https://github.com/pterodactyl/panel/assets/11914187/3434ac10-52f6-4880-ab67-b5bdcc4abca5)

### Steps to Reproduce

I said everything before.

### Panel Version

1.11.5

### Wings Version

1.6.1

### Docker Image

ghcr.io/pterodactyl/panel:latest

### Error Logs

```bash
No error
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.
