### ISSUE TITLE
A query exception was encountered while trying to load settings from the database: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'panel.settings' doesn't exist (Connection: mysql, SQL: select * from `settings`)

### ISSUE THREAD

**Issue by TutorialMan7727** [pterodactyl/panel#5145]
### Current Behavior

Cant log into panel. Gives error
```
[
    {
        "code": "UnexpectedValueException",
        "status": "500",
        "detail": "An unexpected error was encountered while processing this request, please try again."
    }
]
```

### Expected Behavior

Be able to log into pannel

### Steps to Reproduce

Install panel in docker with 
```
version: '3.8'
x-common:
  database:
    &db-environment
    MYSQL_PASSWORD: &db-password "password"
    MYSQL_ROOT_PASSWORD: "not password"
  panel:
    &panel-environment
    APP_URL: "https://pterodactyl"
    APP_TIMEZONE: "Europe/London"
    TRUSTED_PROXIES: "*"

#
# ------------------------------------------------------------------------------------------
# DANGER ZONE BELOW
#
# The remainder of this file likely does not need to be changed. Please only make modifications
# below if you understand what you are doing.
#
services:
  database:
    image: mariadb:10.5
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./database:/var/lib/mysql"
    environment:
      <<: *db-environment
      MYSQL_DATABASE: "panel"
      MYSQL_USER: "pterodactyl"
  cache:
    image: redis:alpine
    restart: always
  panel:
    image: ghcr.io/pterodactyl/panel:latest
    restart: always
    links:
      - database
      - cache
    volumes:
      - "./var/:/app/var/"
      - "./nginx/:/etc/nginx/http.d/"
      - "./certs/:/etc/letsencrypt/"
      - "./logs/:/app/storage/logs"
    environment:
      <<: [*panel-environment]
      DB_PASSWORD: *db-password
      APP_REPORT_ALL_EXCEPTIONS: "true"
      APP_ENV: "production"
      APP_ENVIRONMENT_ONLY: "false"
      CACHE_DRIVER: "redis"
      SESSION_DRIVER: "redis"
      QUEUE_DRIVER: "redis"
      REDIS_HOST: "cache"
      DB_HOST: "database"
      DB_PORT: "3306"

networks:
  default:
    name: all
    external: true
```

### Panel Version

1.11.7

### Wings Version

NA

### Games and/or Eggs Affected

NA

### Docker Image

NA

### Error Logs

```bash
https://pteropaste.com/j8cv
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.
