### ISSUE TITLE
Wings: default log_config: config: options break support for different log drivers

### ISSUE THREAD

**Issue by zmiguel** [pterodactyl/panel#5278]
### Current Behavior

[This is the relevant code line on Wings](https://github.com/pterodactyl/wings/blob/c6c235dbc07341d5f50606819624a2e4770648a7/config/config_docker.go#L93)

On startup Wings always adds 
```
  log_config:
    config:
      compress: "false"
      max-file: "1"
      max-size: 5m
      mode: non-blocking
```
to the config.yml file

### Expected Behavior

If those fields are removed because of the use of a different log-driver wings should not re-add them

### Steps to Reproduce

Configure wings to use a different log-driver, for example Loki

```
  log_config:
    type: loki
    config:
      loki-batch-size: "256"
      loki-url: http://loki:3100/loki/api/v1/push
```

restart Wings

config is now:
```
  log_config:
    type: loki
    config:
      compress: "false"
      loki-batch-size: "256"
      loki-url: http://loki:3100/loki/api/v1/push
      max-file: "1"
      max-size: 5m
      mode: non-blocking
```

Containers fail to start with error:
```
environment/docker: failed to start container: Error response from daemon: failed to create task for container: failed to initialize logging driver: error creating logger: error creating loki logger: loki: wrong log-opt: 'compress'
```

### Panel Version

v1.11.10

### Wings Version

v1.11.13

### Error Logs

```bash

```

### Is there an existing issue for this?

- [x] I have searched the existing issues before opening this issue.
- [x] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [x] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.
