### ISSUE TITLE
Creating database fails in step 2017_03_14_175631_RenameServicePacksToSingluarPacks

### ISSUE THREAD

**Issue by skirmess** [pterodactyl/panel#5318]
### Current Behavior

I'm using the following `docker-compose.yml` file, which is based on [
this](https://github.com/pterodactyl/panel/blob/release/v1.11.10/docker-compose.example.yml). (don't worry about the password, I'll create a new one :-))

```
docker-compose.yml 
x-common:
  database:
    &db-environment
    # Do not remove the "&db-password" from the end of the line below, it is important
    # for Panel functionality.
    MYSQL_PASSWORD: &db-password "TjapS5JGVL6pYJVNNZj6"
    MYSQL_ROOT_PASSWORD: "4hspSKTQVvWtiBAV5Kei"
  panel:
    &panel-environment
    APP_URL: "http://sothis.net.kzone.ch"
    # A list of valid timezones can be found here: http://php.net/manual/en/timezones.php
    APP_TIMEZONE: "Europe/Zurich"
    APP_SERVICE_AUTHOR: "sven.kirmess@kzone.ch"
    # Uncomment the line below and set to a non-empty value if you want to use Let's Encrypt
    # to generate an SSL certificate for the Panel.
    # LE_EMAIL: ""
  mail:
    &mail-environment
    MAIL_FROM: "pterodac@sothis.net.kzone.ch"
    MAIL_DRIVER: "smtp"
    MAIL_HOST: "mailhost.net.kzone.ch"
    MAIL_PORT: "25"
    MAIL_USERNAME: ""
    MAIL_PASSWORD: ""
    MAIL_ENCRYPTION: "true"

#
# ------------------------------------------------------------------------------------------
# DANGER ZONE BELOW
#
# The remainder of this file likely does not need to be changed. Please only make modifications
# below if you understand what you are doing.
#
services:
  database:
    image: mariadb:10.5
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "/l/u/pterodac/pterodactyl/database:/var/lib/mysql"
    environment:
      <<: *db-environment
      MYSQL_DATABASE: "panel"
      MYSQL_USER: "pterodactyl"
  cache:
    image: redis:alpine
    restart: always
  panel:
    #image: ghcr.io/pterodactyl/panel:latest
    image: ghcr.io/pterodactyl/panel:v1.11.10
    restart: always
    ports:
      - "80:80"
      - "443:443"
    links:
      - database
      - cache
    volumes:
      - "/l/u/pterodac/pterodactyl/var/:/app/var/"
      - "/l/u/pterodac/pterodactyl/nginx/:/etc/nginx/http.d/"
      - "/l/u/pterodac/pterodactyl/certs/:/etc/letsencrypt/"
      - "/l/u/pterodac/pterodactyl/logs/:/app/storage/logs"
    environment:
      <<: [*panel-environment, *mail-environment]
      DB_PASSWORD: *db-password
      APP_ENV: "production"
      APP_ENVIRONMENT_ONLY: "false"
      CACHE_DRIVER: "redis"
      SESSION_DRIVER: "redis"
      QUEUE_DRIVER: "redis"
      REDIS_HOST: "cache"
      DB_HOST: "database"
      DB_PORT: "3306"
networks:
  default:
    ipam:
      config:
        - subnet: 172.20.0.0/16
```

When I try to run it with  `docker compose up -d` the database creation fails:

```
panel-1     |   2017_03_14_175631_RenameServicePacksToSingluarPacks .............. 31ms FAIL
```

### Expected Behavior

I would expect the docker image to be able to create the initial database.

### Steps to Reproduce

You should be able to reproduce it with the `docker-compose.yml` from this bug report.

### Panel Version

1.11.10

### Wings Version

none

### Error Logs

- `docker compose logs database`: https://ptero.co/raw/lonitiyuga
- `docker compose logs panel`: https://ptero.co/raw/cocosobuvi
- `docker compose logs cache`: https://ptero.co/raw/domiboyate

### Is there an existing issue for this?

- [x] I have searched the existing issues before opening this issue.
- [x] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [x] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.
